version: '3.8'

services:
  apache:
    image: php:7.4-apache
    container_name: apache_container
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_password
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

